### ISSUE TITLE
[BUG] Timed Out when backend is Forge

### ISSUE THREAD

**Issue by lightumcc** [Elytrium/LimboAPI#150]
**Describe the bug**
I installed following plugins on Velocity (3.3.0-SNAPSHOT Build 386) server and mods on Forge 1.18.2 server, found that timed out on Velocity that is caused by Limbo API, console said that
```bash
[19:47:32 INFO] [limboapi]: lightum_cc (/xxxx:61194) has connected to the LimboFilter Limbo
[19:47:33 INFO] [limbofilter]: [connected player] lightum_cc (/xxxx:61194) has client brand forge
[19:47:34 WARN] [limboapi]: [connected player] lightum_cc (/xxxx:61194) was kicked due to keepalive timeout.
[19:47:34 INFO] [limboapi]: lightum_cc (/xxxx:61194) has disconnected from the LimboFilter Limbo
```

**To Reproduce**
1. Install the following plugins and mods (maybe you can just install the limbo series, I've already tested that this is caused by Limbo API)
2. Start the server and join.

**Expected behavior**
Join the server.

**Screenshots**
<img width="1836" alt="iShot_2024-05-01_19 48 38" src="https://github.com/Elytrium/LimboAPI/assets/60721270/fa907cc4-6104-4e15-b5c1-e607e6dad3c5">

**Server Info (please complete the following information):**
- Velocity Plugins
```
Ambassador-Velocity-1.5.2-beta-all.jar
FastMOTD-1.0.6.jar
limboapi-1.1.23.jar
limboauth-1.1.14-SNAPSHOT.jar
limbofilter-1.1.17.jar
LimboReconnect-1.1.5.jar
LuckPerms-Velocity-5.4.117.jar
MapModCompanion.jar
velocity-tools-1.2.2.jar
```

- Forge Mods
```
proxy-compatible-forge-1.18.2-1.1.4.jar
```

**Comment by UserNugget** [comment]
Looks like you should increase `max-ping` in the limbofilter config, that should fix it

**Comment by lightumcc** [comment]
I tried to add max-ping to `100000`, this issue still happened

**Comment by lightumcc** [comment]
The issue changed to:
1. I passed the limbofilter
2. wait for limboauth (there should have some title context, but nothing found)
3. Timed Out

**Comment by mdxd44** [comment]
it's already known bug with incorrect keep alive handling, i'll try to fix it later

**Comment by mdxd44** [comment]
fixed in 3952869

**Comment by lightumcc** [comment]
I'm sorry bug this issue still happened after I download the latest limboapi from [GitHub Action](https://github.com/Elytrium/LimboAPI/actions/runs/8953435227)
```
[11:12:02 INFO] [limboapi]: lightum_cc (/xxxx:59479) has connected to the LimboFilter Limbo
[11:12:02 INFO] [limbofilter]: [connected player] lightum_cc (/xxxx:59479) has client brand forge
[11:12:08 INFO] [limboapi]: lightum_cc (/xxxx:59479) has disconnected from the LimboFilter Limbo
[11:12:08 INFO] [limboapi]: lightum_cc (/xxxx:59479) has connected to the LimboAuth Limbo
[11:12:09 WARN] [limboapi]: [connected player] lightum_cc (/xxxx:59479) was kicked due to keepalive timeout.
[11:12:09 INFO] [limboapi]: lightum_cc (/xxxx:59479) has disconnected from the LimboAuth Limbo
```
My `max-ping` and `time-out` in limbofilter have been set to `1000000000`

**Comment by mdxd44** [comment]
is it happens only with forge?

**Comment by lightumcc** [comment]
From my testing so far, yes.

**Comment by mdxd44** [comment]
try this build and show me the logs
[limboapi-1.1.23.zip](https://github.com/Elytrium/LimboAPI/files/15212622/limboapi-1.1.23.zip)

**Comment by lightumcc** [comment]
```
[19:14:02 INFO] [limboapi]: lightum_cc (/xxxx:64509) has connected to the LimboFilter Limbo
[19:14:02 INFO]: serverReadTimeout: 1000000000
[19:14:02 INFO]: getServer().getConfiguration().getReadTimeout(): 30000
[19:14:02 INFO]: scheduling keep alive task: 1000000000
[19:14:03 INFO]: keepAlivePending sentTime: 1714907643233, keepAliveKey: 1257442958
[19:14:03 INFO] [limbofilter]: [connected player] lightum_cc (/xxxx:64509) has client brand forge
[19:14:10 INFO] [limboapi]: lightum_cc (/xxxx:64509) has disconnected from the LimboFilter Limbo
[19:14:10 INFO] [limboapi]: lightum_cc (/xxxx:64509) has connected to the LimboAuth Limbo
[19:14:10 INFO]: moving:
[19:14:10 INFO]: keepAliveKey: 1257442958
[19:14:10 INFO]: keepAlivePending: true
[19:14:10 INFO]: keepAliveSentTime: 1714907643233
[19:14:10 INFO]: ping: -1
[19:14:10 INFO]: serverReadTimeout: null
[19:14:10 INFO]: getServer().getConfiguration().getReadTimeout(): 30000
[19:14:10 INFO]: scheduling keep alive task: 15000
[19:14:10 INFO]: keepAlivePending true
[19:14:10 WARN] [limboapi]: [connected player] lightum_cc (/xxxx:64509) was kicked due to keepalive timeout.
[19:14:10 INFO] [limboapi]: lightum_cc (/xxxx:64509) has disconnected from the LimboAuth Limbo
```

**Comment by mdxd44** [comment]
try this one
[limboapi-1.1.23.zip](https://github.com/Elytrium/LimboAPI/files/15212676/limboapi-1.1.23.zip)

**Comment by lightumcc** [comment]
This time I lasted a little longer in limboauth but still ended up getting kicked out, in the meantime I saw the limbofilter title text but once in limboauth it went blank until I was kicked out.

```
[19:28:58 INFO] [limboapi]: lightum_cc (/xxxx:52370) has connected to the LimboFilter Limbo
[19:28:58 INFO] [limbofilter]: [connected player] lightum_cc (/xxxx:52370) has client brand forge
[19:29:05 INFO] [limboapi]: lightum_cc (/xxxx:52370) has disconnected from the LimboFilter Limbo
[19:29:05 INFO] [limboapi]: lightum_cc (/xxxx:52370) has connected to the LimboAuth Limbo
[19:29:20 WARN] [limboapi]: [connected player] lightum_cc (/xxxx:52370) was kicked due to keepalive timeout.
[19:29:20 INFO] [limboapi]: lightum_cc (/xxxx:52370) has disconnected from the LimboAuth Limbo
```

**Comment by mdxd44** [comment]
try increase read-timeout in velocity.toml

**Comment by lightumcc** [comment]
Now I increased `read-timeout` to 100000000

```
[19:33:53 INFO] [limboapi]: lightum_cc (/xxxx:53758) has connected to the LimboFilter Limbo
[19:33:53 INFO] [limbofilter]: [connected player] lightum_cc (/10.20.50.100:53758) has client brand forge
[19:34:00 INFO] [limboapi]: lightum_cc (/xxxx:53758) has disconnected from the LimboFilter Limbo
[19:34:00 INFO] [limboapi]: lightum_cc (/xxxx:53758) has connected to the LimboAuth Limbo
[19:34:30 INFO] [limboapi]: lightum_cc (/xxxx:53758) has disconnected from the LimboAuth Limbo
[19:34:30 INFO]: [initial connection] /xxxx:53758 has disconnected
```

**Comment by mdxd44** [comment]
I noticed that ambasador is listed in the list of plugins. Perhaps this problem occurs due to incompatibility with that plugin? try to remove it

**Comment by lightumcc** [comment]
Amazing! This issue has been fixed!

Maybe I shouldn't have trusted the introductory note from `[Proxy Compatible Forge](https://modrinth.com/mod/proxy-compatible-forge)` in the first place, and it got me in trouble!

I'm sorry for wasting your precious time this weekend.

**Comment by mdxd44** [comment]
anyway thanks to you I finally fixed the incorrect keep alive handling
